name: RuboCop auto-correct
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-
      - name: Install dependencies
        run: |
          bundle config set path vendor/bundle
          bundle install -j4
      - name: RuboCop auto-correct
        env:
          OCTOKIT_ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
        run: |
          bin/rubocop_auto_correct_pull_request
